### ISSUE TITLE
Created 0 sprite(s) from 0 images, saved 0% requests

### ISSUE THREAD

**Issue by hannesClown** [gobwas/gulp-sprite-generator#8]
Hi,

I use this one but I get no sprite:

// create sprite image
gulp.task('sprites', function() {
    var spriteOutput;
 
    spriteOutput = gulp.src("build/css/rateit.css")
        .pipe(sprite({
            baseUrl:         "build/img/",
            spriteSheetName: "sprite.png",
            spriteSheetPath: "build/image"
        }));
 
    spriteOutput.css.pipe(gulp.dest("build/css/gen"));
    spriteOutput.img.pipe(gulp.dest("build/image"));
});

The thing is when I use only the spritesmith I get a wonderful sprite.

Would be nice if anyone has an idea!

**Comment by gobwas** [comment]
Hi!

Does relative path to images inside your `rateit.css` links to inside `build/img`?

The option `baseUrl`, from spec:

> Defines where to find relatively defined image references in the input stylesheet.

**Comment by gobwas** [comment]
@hannesClown ping
